name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  FOUNDRY_PROFILE: ci

jobs:
  lint:
    name: Lint contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge format
        run: |
          cd contracts
          forge --version
          forge fmt
        id: fmt

  test:
    strategy:
      fail-fast: true

    name: Test contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd contracts
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd contracts
          forge test -vvv
        id: test
